# Generated by Django 4.2.7 on 2023-11-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('qns', models.TextField()),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField()),
                ('qns1', models.TextField()),
                ('ans1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n10', models.IntegerField()),
                ('qns10', models.TextField()),
                ('ans10', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n2', models.IntegerField()),
                ('qns2', models.TextField()),
                ('ans2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n3', models.IntegerField()),
                ('qns3', models.TextField()),
                ('ans3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n4', models.IntegerField()),
                ('qns4', models.TextField()),
                ('ans4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n5', models.IntegerField()),
                ('qns5', models.TextField()),
                ('ans5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n6', models.IntegerField()),
                ('qns6', models.TextField()),
                ('ans6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n7', models.IntegerField()),
                ('qns7', models.TextField()),
                ('ans7', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n8', models.IntegerField()),
                ('qns8', models.TextField()),
                ('ans8', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n9', models.IntegerField()),
                ('qns9', models.TextField()),
                ('ans9', models.CharField(max_length=50)),
            ],
        ),
    ]
